import { Save, X } from "lucide-react";
import { useEffect, useState, type FormEvent } from "react";
import type { PaidModule } from "@/lib/paid-course-types";

export function ModuleForm({ courseId, courseSlug, editing, onSaved, onCancel }: { courseId: string; courseSlug: string; editing?: PaidModule | null; onSaved: (record: any) => Promise<void>; onCancel: () => void }) {
  const [form, setForm] = useState({ title: "", description: "", sort_order: 1, is_published: true });
  const [error, setError] = useState(""); const [saving, setSaving] = useState(false);
  useEffect(() => { setForm({ title: "", description: "", sort_order: 1, is_published: true, ...editing }); setError(""); }, [editing]);
  const update = (key: string, value: any) => setForm((current) => ({ ...current, [key]: value }));
  const submit = async (event: FormEvent) => { event.preventDefault(); if (!form.title.trim()) { setError("Add a module title."); return; } const order = Number(form.sort_order); if (!Number.isInteger(order) || order < 1) { setError("Display order must be a whole number greater than zero."); return; } setSaving(true); setError(""); try { await onSaved({ course_id: courseId, course_slug: courseSlug, title: form.title.trim(), description: form.description.trim(), sort_order: order, is_published: Boolean(form.is_published) }); } catch (saveError) { console.error("Failed to save module:", saveError); setError("The module could not be saved. Try again."); } finally { setSaving(false); } };
  return <form onSubmit={submit} className="surface p-5"><div className="flex items-start justify-between gap-3"><div><p className="eyebrow">{editing ? "Edit module" : "New module"}</p><h3 className="mt-2 font-display text-xl font-bold text-[#14294d]">Course module</h3></div><button type="button" className="button-quiet !min-h-10 !min-w-10 !p-2" onClick={onCancel} aria-label="Close module form"><X size={18} /></button></div>{error && <p className="mt-4 rounded-xl bg-rose-50 p-3 text-xs font-semibold text-rose-700" role="alert">{error}</p>}<label className="mt-5 block text-xs font-bold text-slate-600" htmlFor="module-title">Title<input id="module-title" value={form.title} onChange={(event) => update("title", event.target.value)} className="mt-2 h-11 w-full rounded-xl border border-slate-200 px-3 text-sm outline-none focus:border-sky-400" /></label><label className="mt-4 block text-xs font-bold text-slate-600" htmlFor="module-description">Description<textarea id="module-description" rows={3} value={form.description} onChange={(event) => update("description", event.target.value)} className="mt-2 w-full rounded-xl border border-slate-200 p-3 text-sm outline-none focus:border-sky-400" /></label><div className="mt-4 grid gap-3 sm:grid-cols-2"><label className="text-xs font-bold text-slate-600" htmlFor="module-order">Display order<input id="module-order" type="number" min="1" step="1" value={form.sort_order} onChange={(event) => update("sort_order", event.target.value)} className="mt-2 h-11 w-full rounded-xl border border-slate-200 px-3 text-sm outline-none focus:border-sky-400" /></label><label className="flex min-h-11 items-center gap-3 self-end rounded-xl border border-slate-200 p-3 text-xs font-bold text-slate-600"><input type="checkbox" checked={Boolean(form.is_published)} onChange={(event) => update("is_published", event.target.checked)} className="h-4 w-4 accent-[#1766a9]" /> Visible in preview</label></div><div className="mt-5 flex gap-3"><button type="submit" disabled={saving} className="button-primary"><Save size={15} /> {saving ? "Saving…" : editing ? "Save module" : "Add module"}</button><button type="button" className="button-secondary" onClick={onCancel}>Cancel</button></div></form>;
}
